- name: GIT clone errbit repository
  git: repo={{ deploy_errbit_githuburl }}
       dest={{ deploy_errbit_homedir }}
       version=d533719

- name: MongoDB init script hack
  lineinfile: dest=/etc/init/mongod.conf
    regexp='pre-start script'
    insertafter='^pre-start script'
    line='pre-start script\n touch /var/run/mongod.pid && chmod 0777 /var/run/mongod.pid'
    state=present
  notify: start errbit

- name: Install Bundler
  command: /usr/bin/gem2.1 install bundler

- name: Bundle install
  command: /usr/local/bin/bundle install
  args:
    chdir: '{{ deploy_errbit_homedir }}'
  register: bundleout

- name: Bundle exec
  command: /usr/local/bin/bundle exec rake errbit:bootstrap
  args:
    chdir: '{{ deploy_errbit_homedir }}'
  register: dbing

- debug: msg= '{{ dbing.stdout }}'

- name: Write bundle log
  copy:
    content: '{{ dbing }}'
    dest: '/home/vagrant/bundle.log'

- name: Copy the init script
  copy: src=errbit-init dest=/etc/init/errbit.conf owner=root group=root mode=0755

- name: Copy the startup script
  copy: src=starterrbit dest=/usr/local/bin/starterrbit owner=root group=root mode=0755

- name: Delete default Nginx config
  file: path=/etc/nginx/sites-enabled/default state=absent
    
- name: Setup Nginx virtualhost
  copy: src=files/nginx-errbit.conf dest=/etc/nginx/sites-enabled/errbit.conf owner=root group=root mode=0755
  notify: restart nginx
